config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  validates :name, uniqueness: { message: 'その名前は使用できません' }, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!,except:[:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  user_path(resource)
end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
    def index
      @book = Book.new
      @books = Book.all
      @user = current_user
      @book.user = current_user
    end

    def show
      @book = Book.find(params[:id])
      @book_new = Book.new
      @user = @book.user
    end

    def edit
      @book = Book.find(params[:id])
      @user = @book.user
      unless @user.id == current_user.id
        redirect_to books_path
      end
    end

    def new
      @book = Book.new
    end

    def create
      @books = Book.all
      @book = Book.new(book_params)
      @book.user_id = current_user.id
       if @book.save
         flash[:notice] = "You have created book successfully."
         redirect_to book_path(@book)
       else
         @user = current_user
         render :index
       end
    end

    def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
        flash[:notice] = "You have updated book successfully."
        redirect_to book_path(@book.id)
      else
        render :edit
      end
    end

    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
    end
  private


  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end

  end

  private



  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
        <% if @book.errors.any? %>
          <%= @book.errors.count %>件のerrorが発生しました
          <% @book.errors.full_messages.each do |message| %>
          <li class="error-messages"><%= message %></li>
         <% end %>
        <% end %>
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_image.jpg"%>
        <table class="table">
         <tbody>
           <tr></tr>
           <tr>
             <th>name</th>
             <th><%= @user.name %></th>
           </tr>
           <tr>
             <th>introduction</th>
             <th><%= @user.introduction %></th>
           </tr>
         </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:book, local:true do |f| %>
          <div class="from">
            <p class="text">Title</p>
            <%= f.text_field :title, class: "form-control book_title" %>
          </div>
          <div class="from">
            <p class="text">Opinion</p>
            <%= f.text_area :body, class: "form-control book_body" %>
          </div>
          <div class="from">
            <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
          </div>
        <% end %>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
         <%= @book.errors.count %>件のerrorが発生しました
         <% @book.errors.full_messages.each do |message| %>
         <li class="error-messages"><%= message %></li>
         <% end %>
        <% end %>
        <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <h4>Title</h4>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <h4>Opinion</h4>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit'Update Book', class: "btn btn-secondary" %>
        </div>
        <% end %>
        <%= link_to "Show", book_path(@book) %>
         |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <% if @book.errors.any? %>
      <%= @book.errors.count %>件のerrorが発生しました
      <% @book.errors.full_messages.each do |message| %>
      <li class="error-messages"><%= message %></li>
      <% end %>
    <% end %>
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @book.user, :profile_image, size: '100x100', fallback: "no_image.jpg"%>
        <table class="table">
         <tbody>
           <tr></tr>
           <tr>
             <th>name</th>
             <th><%= @user.name %></th>
           </tr>
           <tr>
             <th>introduction</th>
             <th><%= @user.introduction %></th>
           </tr>
         </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book, local:true do |f| %>
          <div class="from">
            <p>Title</p>
            <%= f.text_field :title %>
          </div>
          <div class="from">
            <p>Opinion</p>
            <%= f.text_area :body %>
          </div>
          <div class="from">
            <%= f.submit 'Create Book' %>
          </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                  <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, size: '40x40', fallback: "no_image.jpg" %>
                  <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list',book: @book_new %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, size: '40x40', fallback: "no_image.jpg" %>
                <% end %>
                <br><%= link_to @user.name, user_path(@book.user) %>
              </td>
              <td><%= link_to @book.title, book_path(@book) %></td>
              <td><%= @book.body %></td>
              <% if user_signed_in? && current_user.id == @book.user_id %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
              <p class="font">In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
              <p class="font">you can share and exchange  your opinions , inpressions , and emotions</p>
              <p class="font"> about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
              <div class="row">
                <%= link_to "Log in", "/users/sign_in", class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
              </div>
              <div class="row">
                <%= link_to "Sign Up", "/users/sign_up", class: "btn btn-success btn-sm btn-block sign_up" %>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
             <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="fas fa-home nav-link text-light">
                <%= link_to "Home", user_path(current_user.id) %>
              </li>
              <li class="fas fa-users nav-link text-light">
                <%= link_to "Users", users_path %>
              </li>
              <li class="fas fa-book-open nav-link text-light">
                <%= link_to "Books", books_path %>
              </li>
              <li class="fas fa-sign-out-alt nav-link text-light">
                <%= link_to "logout", destroy_user_session_path, method: :delete %>
              </li>
              <% else %>
              <li class="fas fa-home nav-link text-light">
                <%= link_to "Home", root_path %>
              </li>
              <li class="fas fa-link nav-link text-light">
                <%= link_to "About", home_about_path %>
              </li>
              <li class="fas fa-user-plus nav-link text-light">
                <%= link_to "sign up", new_user_registration_path %>
              </li>
              <li class="fas fa-sign-in-alt nav-link text-light">
                <%= link_to "login", new_user_session_path %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="notice">
      <% flash.each do |key, valie| %>
        <%= content_tag(:div, valie, class: "#{key}") %>
      <% end %>
      </div>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
    	  <div class="row">
    	    <div class="mx-auto">
    		    <p class="font">CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? %>
         <%= @user.errors.count %>件のerrorが発生しました
         <% @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
        <% end %>
          <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <p for="inputName">Name</p>
            <%= f.text_field :name, autofocus: true, class: "form-control name" %>
          </div>
          <div class="form-group">
            <p for="inputImage">Image</p>
            <%= f.attachment_field :profile_image %>
          </div>
          <div class="form-group">
            <p for="inputIntroduction">Introduction</p>
            <%= f.text_area :introduction, class: "form-control introduction" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, size: '40x40', fallback: "no_image.jpg" %>
                </td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, size: '40x40', fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</main>